### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by TacoCraftxD** [acgd-learn-the-web/topics#10]
When going to [https://learn-the-web.algonquindesign.ca/activities/install-more-developer-tools](https://learn-the-web.algonquindesign.ca/activities/install-more-developer-tools) you get a 404. I found this url from [https://learn-the-web.algonquindesign.ca/activities/](https://learn-the-web.algonquindesign.ca/activities/) in Web Dev 4

**Comment by TacoCraftxD** [comment]
👍

**Comment by thomasjbradley** [comment]
Thanks! I’ve fixed the problem.

**Comment by TacoCraftxD** [comment]
Still get a 404 :( 
![image](https://user-images.githubusercontent.com/32072697/65521971-5453c380-deea-11e9-95d5-0f6311aec965.png)
![image](https://user-images.githubusercontent.com/32072697/65521989-5d449500-deea-11e9-8bf9-16a1ad599fd1.png)

**Comment by thomasjbradley** [comment]
Yes, because it’s not actually an activity. It was mis-categorized & shouldn’t be showing on the activities page. You can see the correct URL right on the 404 page there—it’s a step-by-step lesson exploring installation of Homebrew & Ruby.

**Comment by thomasjbradley** [comment]
I’m really happy to hear that the Jekyll & NetlifyCMS lessons were helpful for you.
